import { CssBaseline, ThemeProvider } from '@mui/material';
import type { Metadata } from 'next';
import { darkTheme } from '../themes';
import { NextAuthProvider } from '../provider';
import { TopLayout } from '../layouts';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="jp">
			<ThemeProvider theme={darkTheme}>
				<body>
					<NextAuthProvider>
						<TopLayout>
							<CssBaseline />
							{children}
						</TopLayout>
					</NextAuthProvider>
				</body>
			</ThemeProvider>
		</html>
	);
}
